version: '3.8'
services:
  mongo:
    image: mongo
    container_name: simpleshop
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - D:\code\data\docker-mongoDB-simpleshop:/data/db
