services:
  postgres:
    image: postgres
    container_name: simpleshop_postgresql
    restart: always
    environment:
      POSTGRES_USER: database_admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: simpleshop_database
    ports:
      - "55555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
