spring.application.name=simpleshop
spring.datasource.url=jdbc:postgresql://localhost:55555/simpleshop_database
spring.datasource.username=database_admin
spring.datasource.password=test
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true